Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.network "forwarded_port", guest: 27017, host: 27017
  config.vm.provision "docker" do |d|
    d.run "mongoDB", image: "mongo:latest", args: "-p 27017:27017"
  end

end